### PR TITLE
Update kfs notebook with ART example

### PR DESCRIPTION
**Pull request by drewbutlerbb4**

### CODE REVIEW

**Comment by drewbutlerbb4** [comment]
@Tomcli

**Comment by Tomcli** [comment]
@drewbutlerbb4 I merged your last PR so there might be some duplicated code in master already. Can you rebase/merge with the latest master?

**Comment by drewbutlerbb4** [comment]
@Tomcli Looks good now?

**Comment by Tomcli** [comment]
@drewbutlerbb4 so looks like the changes is already in master from your previous PR, do you still need to merge it?

**Comment by drewbutlerbb4** [comment]
Yep, you are right. Thanks

**Pull request closed without merging**
